// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Obeysoft.Infrastructure.Persistence;

#nullable disable

namespace Obeysoft.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20251031205000_AddUserProfiles")]
    partial class AddUserProfiles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Obeysoft.Domain.Users.UserProfile", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid");
                    b.Property<int?>("Age").HasColumnType("integer");
                    b.Property<string>("AvatarUrl").HasColumnType("text");
                    b.Property<string>("City").HasColumnType("text");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Gender").HasColumnType("text");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("timestamp with time zone");

                    b.HasKey("Id");
                    b.HasIndex("UserId").IsUnique();
                    b.ToTable("UserProfiles", (string)null);
                });
        }
    }
}


